swagger: '2.0'
info:
  title: Transformer wrapper API for gene shapener 
  version: 1.0.0

paths:
  /transformer_info:
    get:
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/transformer_info'

  /transform:
    post:
      parameters:
      - in: body
        name: query
        description: transformer query
        required: true
        schema:
          $ref: '#/definitions/transformer_query'

      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/gene_info'
        
definitions:

  transformer_query:
    type: object
    properties:
      genes:
        type: array
        items:
          $ref: '#/definitions/gene_info'
      controls:
        type: array
        items:
          $ref: '#/definitions/property'

  gene_info:
    type: object
    properties:
      gene_id:
        type: string
      attributes:
        type: array
        items:
          $ref: '#/definitions/attribute'
    required: 
      - gene_id

  attribute:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      source:
        type: string

  property:
    type: object
    properties:
      name:
        type: string
      value:
        type: string

  transformer_info:
    type: object
    properties:
      name:
        type: string
      function:
        type: string
      parameters:
        type: array
        items:
          $ref: '#/definitions/parameter'

  parameter:
    type: object
    properties:
      name:
        type: string
      type:
        type: string
      default:
        type: string
      allowed_values: 
        type: array
        items:
          type: string
